// Usage:
//   pnpm generate:rule-table          # regenerate the table
//   pnpm generate:rule-table:check    # check if the table is up to date

import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import * as v from "valibot";

import { preset } from "../src/preset.ts";
import {
  oxlintVersion as prevVersion,
  ruleTable as prevTable,
} from "../src/rule-table.generated.ts";
import type { CategoryName, PluginName, RuleInfo, RuleTable } from "../src/rule-table.ts";
import { isCategoryName, isPluginName } from "../src/rule-table.ts";

const require = createRequire(import.meta.url);
const rootDir = fileURLToPath(new URL("..", import.meta.url));
const outFile = path.join(rootDir, "src", "rule-table.generated.ts");

function oxlintVersion(): string {
  const pkg: unknown = require("oxlint/package.json");
  return v.parse(v.object({ version: v.string() }), pkg).version;
}

const pluginName = v.custom<PluginName>(
  (input) => typeof input === "string" && isPluginName(input),
);
const categoryName = v.custom<CategoryName>(
  (input) => typeof input === "string" && isCategoryName(input),
);

const ruleListSchema = v.array(
  v.object({
    // The CLI prints plugin names with underscores (e.g. `jsx_a11y`), while configs use hyphens.
    scope: v.pipe(
      v.string(),
      v.transform((scope) => scope.replaceAll("_", "-")),
      pluginName,
    ),
    value: v.string(),
    category: categoryName,
    type_aware: v.boolean(),
  }),
);

function listRules(): RuleTable {
  const json = execFileSync("pnpm", ["exec", "oxlint", "--rules", "-f", "json"], {
    cwd: rootDir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  });
  const table: Record<string, RuleInfo> = {};
  for (const item of v.parse(ruleListSchema, JSON.parse(json))) {
    const { scope: plugin, value: rule, category, type_aware: typeAware } = item;
    const name = plugin === "eslint" ? rule : `${plugin}/${rule}`;
    if (Object.hasOwn(table, name)) {
      throw new Error(`Duplicate rule: ${name}`);
    }
    table[name] = { plugin, category, typeAware };
  }
  return table;
}

function render(version: string, table: RuleTable): string {
  const entries = Object.entries(table)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, info]) => {
      const plugin = JSON.stringify(info.plugin);
      const category = JSON.stringify(info.category);
      const typeAware = JSON.stringify(info.typeAware);
      return `  ${JSON.stringify(name)}: { plugin: ${plugin}, category: ${category}, typeAware: ${typeAware} },`;
    });
  return [
    "// Generated by `pnpm generate:rule-table`. Do not edit manually.",
    `// Source: oxlint ${version}`,
    "",
    'import type { RuleTable } from "./rule-table.ts";',
    "",
    `export const oxlintVersion = ${JSON.stringify(version)};`,
    "",
    "export const ruleTable: RuleTable = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function presetRuleNames(): Set<string> {
  const names = new Set<string>();
  for (const pluginPreset of Object.values(preset)) {
    for (const name of Object.keys(pluginPreset.rules ?? {})) {
      names.add(name);
    }
    for (const [name, superseded] of Object.entries(pluginPreset.supersedes ?? {})) {
      names.add(name);
      for (const s of superseded) {
        names.add(s);
      }
    }
  }
  return names;
}

function describe(info: RuleInfo): string {
  return `${info.category}${info.typeAware ? ", type-aware" : ""}`;
}

function reportDiff(version: string, table: RuleTable): void {
  const referenced = presetRuleNames();
  const mark = (name: string): string => (referenced.has(name) ? "  [referenced by preset]" : "");

  const added = Object.keys(table)
    .filter((name) => !Object.hasOwn(prevTable, name))
    .map((name) => {
      const info = table[name];
      return `  + ${name}  (${info === undefined ? "?" : describe(info)})`;
    });
  const removed = Object.keys(prevTable)
    .filter((name) => !Object.hasOwn(table, name))
    .map((name) => {
      const info = prevTable[name];
      return `  - ${name}  (${info === undefined ? "?" : describe(info)})` + mark(name);
    });
  const changed = Object.entries(table).flatMap(([name, info]) => {
    const old = prevTable[name];
    if (old === undefined) {
      return [];
    }
    const diffs = [
      ...(old.plugin !== info.plugin ? [`plugin: ${old.plugin} -> ${info.plugin}`] : []),
      ...(old.category !== info.category ? [`category: ${old.category} -> ${info.category}`] : []),
      ...(old.typeAware !== info.typeAware
        ? [`typeAware: ${old.typeAware} -> ${info.typeAware}`]
        : []),
    ];
    return diffs.length > 0 ? [`  ~ ${name}  ${diffs.join(", ")}` + mark(name)] : [];
  });

  console.log(`oxlint ${prevVersion} -> ${version}`);
  console.log(`Added rules (${added.length}):`);
  for (const line of added) {
    console.log(line);
  }
  console.log(`Removed rules (${removed.length}):`);
  for (const line of removed) {
    console.log(line);
  }
  console.log(`Changed rules (${changed.length}):`);
  for (const line of changed) {
    console.log(line);
  }
}

async function main(): Promise<void> {
  const { values: opts } = parseArgs({
    options: {
      check: { type: "boolean", default: false },
    },
  });

  const version = oxlintVersion();
  const table = listRules();
  const source = render(version, table);
  const relOutFile = path.relative(rootDir, outFile);

  if (opts.check) {
    const prevSource = await readFile(outFile, "utf8");
    if (prevSource === source) {
      console.log(`${relOutFile} is up to date (oxlint ${version})`);
      return;
    }
    console.error(`${relOutFile} is out of date; run \`pnpm generate:rule-table\``);
    reportDiff(version, table);
    process.exitCode = 1;
    return;
  }

  await writeFile(outFile, source);
  console.log(`Wrote ${relOutFile} (${Object.keys(table).length} rules)`);
  reportDiff(version, table);
}

await main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
