import type { DummyRuleMap } from "oxlint";

import type { PluginName } from "./rule-table.ts";

export type PluginPreset = Readonly<{
  rules?: DummyRuleMap;
  supersedes?: Readonly<Record<string, readonly string[]>>;
}>;

export type Preset = Readonly<Partial<Record<PluginName, PluginPreset>>>;

export const preset: Preset = {
  eslint: {
    rules: {
      // correctness
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-caller": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-const-assign": "error",
      "no-constant-binary-expression": ["error", { checkRelationalComparisons: true }],
      "no-constant-condition": ["error", { checkLoops: "allExceptWhileTrue" }],
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-eval": ["error", { allowIndirect: false }],
      "no-ex-assign": "error",
      "no-extra-boolean-cast": ["error", { enforceForInnerExpressions: true }],
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": ["error", { allowEscape: true }],
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-self-assign": ["error", { props: true }],
      "no-setter-return": "error",
      "no-shadow-restricted-names": ["error", { reportGlobalThis: true }],
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unassigned-vars": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: false,
          allowTaggedTemplates: false,
          allowTernary: false,
          enforceForJSX: true,
          ignoreDirectives: false,
        },
      ],
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": [
        "error",
        {
          args: "after-used",
          caughtErrors: "all",
          vars: "all",
          ignoreClassWithStaticInitBlock: false,
          ignoreRestSiblings: true,
          ignoreUsingDeclarations: true,
          reportUsedIgnorePattern: true,
          reportVarsOnlyUsedAsTypes: true,
        },
      ],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-with": "error",
      "require-yield": "warn",
      "use-isnan": ["error", { enforceForIndexOf: true, enforceForSwitchCase: true }],
      "valid-typeof": ["error", { requireStringLiterals: true }],
    },
  },
  oxc: {
    rules: {
      // correctness
      "oxc/bad-array-method-on-arguments": "error",
      "oxc/bad-char-at-comparison": "error",
      "oxc/bad-comparison-sequence": "error",
      "oxc/bad-match-all-arg": "error",
      "oxc/bad-min-max-func": "error",
      "oxc/bad-object-literal-comparison": "error",
      "oxc/bad-replace-all-arg": "error",
      "oxc/const-comparisons": "error",
      "oxc/double-comparisons": "error",
      "oxc/erasing-op": "error",
      "oxc/missing-throw": "error",
      "oxc/number-arg-out-of-range": "error",
      "oxc/only-used-in-recursion": "error",
      "oxc/uninvoked-array-callback": "error",
    },
  },
  typescript: {
    rules: {
      // correctness
      "typescript/await-thenable": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-base-to-string": ["error", { checkUnknown: false }],
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-duplicate-type-constituents": [
        "error",
        { ignoreIntersections: false, ignoreUnions: false },
      ],
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-floating-promises": [
        "error",
        { checkThenables: true, ignoreIIFE: false, ignoreVoid: false },
      ],
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-meaningless-void-operator": ["error", { checkNever: true }],
      "typescript/no-misused-new": "error",
      "typescript/no-misused-spread": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-this-alias": ["error", { allowDestructuring: false }],
      "typescript/no-unnecessary-parameter-property-assignment": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/no-useless-default-assignment": "error",
      "typescript/no-useless-empty-export": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/require-array-sort-compare": ["error", { ignoreStringArrays: true }],
      "typescript/restrict-template-expressions": [
        "error",
        {
          allowAny: false,
          allowArray: false,
          allowBoolean: false,
          allowNever: false,
          allowNullish: false,
          allowNumber: true,
          allowRegExp: false,
        },
      ],
      "typescript/triple-slash-reference": [
        "error",
        { lib: "always", path: "never", types: "prefer-import" },
      ],
      "typescript/unbound-method": ["error", { ignoreStatic: false }],
    },
    supersedes: {
      "typescript/await-thenable": ["unicorn/no-unnecessary-await"],
      "typescript/no-implied-eval": ["no-implied-eval"],
    },
  },
  unicorn: {
    rules: {
      // correctness
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-invalid-fetch-options": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-spread": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
    },
  },
};
