import type { DummyRuleMap } from "oxlint";

import type { PluginName } from "./rule-table.ts";

export type PluginPreset = Readonly<{
  rules?: DummyRuleMap;
  supersedes?: Readonly<Record<string, readonly string[]>>;
}>;

export type Preset = Readonly<Partial<Record<PluginName, PluginPreset>>>;

export const preset: Preset = {
  eslint: {
    rules: {
      // # correctness
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-caller": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-const-assign": "error",
      "no-constant-binary-expression": ["error", { checkRelationalComparisons: true }],
      "no-constant-condition": ["error", { checkLoops: "allExceptWhileTrue" }],
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-eval": ["error", { allowIndirect: false }],
      "no-ex-assign": "error",
      "no-extra-boolean-cast": ["error", { enforceForInnerExpressions: true }],
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": ["error", { allowEscape: true }],
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-self-assign": ["error", { props: true }],
      "no-setter-return": "error",
      "no-shadow-restricted-names": ["error", { reportGlobalThis: true }],
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unassigned-vars": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: false,
          allowTaggedTemplates: false,
          allowTernary: false,
          enforceForJSX: true,
          ignoreDirectives: false,
        },
      ],
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": [
        "error",
        {
          args: "after-used",
          caughtErrors: "all",
          vars: "all",
          ignoreClassWithStaticInitBlock: false,
          ignoreRestSiblings: true,
          ignoreUsingDeclarations: true,
          reportUsedIgnorePattern: true,
          reportVarsOnlyUsedAsTypes: true,
        },
      ],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-with": "error",
      "require-yield": "warn",
      "use-isnan": ["error", { enforceForIndexOf: true, enforceForSwitchCase: true }],
      "valid-typeof": ["error", { requireStringLiterals: true }],

      // # suspicious
      "block-scoped-var": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-implied-eval": "error",
      "no-new": "error",
      "no-shadow": [
        "warn",
        {
          builtinGlobals: true,
          hoist: "functions-and-types",
          ignoreFunctionTypeParameterNameValueShadow: true,
          ignoreOnInitialization: false,
          ignoreTypeValueShadow: true,
        },
      ],
      "no-underscore-dangle": [
        "warn",
        {
          allowAfterSuper: false,
          allowAfterThis: false,
          allowAfterThisConstructor: false,
          allowFunctionParams: false,
          allowInArrayDestructuring: false,
          allowInObjectDestructuring: false,
          allowInUsingDeclarations: false,
          enforceInClassFields: true,
          enforceInMethodNames: true,
        },
      ],
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": ["error", { checkConditionalExpressions: false }],
      "no-unneeded-ternary": ["error", { defaultAssignment: false }],
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "preserve-caught-error": ["error", { requireCatchParameter: true }],

      // # pedantic
      "accessor-pairs": "off",
      "array-callback-return": [
        "error",
        { allowImplicit: false, allowVoid: false, checkForEach: false },
      ],
      eqeqeq: ["error", "always"],
      "max-classes-per-file": "off",
      "max-depth": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "no-array-constructor": "error",
      "no-case-declarations": "error",
      "no-constructor-return": "error",
      "no-else-return": "off",
      "no-fallthrough": "error",
      "no-inline-comments": "off",
      "no-inner-declarations": ["error", "both"],
      "no-lonely-if": "off",
      "no-loop-func": "error",
      "no-negated-condition": "off",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-promise-executor-return": ["error", { allowVoid: false }],
      "no-prototype-builtins": "error",
      "no-redeclare": ["error", { builtinGlobals: true }],
      "no-self-compare": "error",
      "no-throw-literal": "error",
      "no-useless-return": "error",
      "no-warning-comments": "warn",
      "prefer-promise-reject-errors": ["error", { allowEmptyReject: false }],
      radix: ["error", "always"],
      "require-await": "warn",
      "require-unicode-regexp": "error",
      "sort-vars": "off",
      "symbol-description": "error",
    },
  },
  oxc: {
    rules: {
      // # correctness
      "oxc/bad-array-method-on-arguments": "error",
      "oxc/bad-char-at-comparison": "error",
      "oxc/bad-comparison-sequence": "error",
      "oxc/bad-match-all-arg": "error",
      "oxc/bad-min-max-func": "error",
      "oxc/bad-object-literal-comparison": "error",
      "oxc/bad-replace-all-arg": "error",
      "oxc/const-comparisons": "error",
      "oxc/double-comparisons": "error",
      "oxc/erasing-op": "error",
      "oxc/missing-throw": "error",
      "oxc/number-arg-out-of-range": "error",
      "oxc/only-used-in-recursion": "error",
      "oxc/uninvoked-array-callback": "error",

      // # suspicious
      "oxc/approx-constant": "error",
      "oxc/misrefactored-assign-op": "error",
      "oxc/no-async-endpoint-handlers": "error",
      "oxc/no-this-in-exported-function": "error",
    },
  },
  typescript: {
    rules: {
      // # correctness
      "typescript/await-thenable": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-base-to-string": [
        "error",
        // allow `String(x)` on unkown values, e.g. caught errors (not strictly safe though)
        { checkUnknown: false },
      ],
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-duplicate-type-constituents": [
        "error",
        { ignoreIntersections: false, ignoreUnions: false },
      ],
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-floating-promises": [
        "error",
        { checkThenables: true, ignoreIIFE: false, ignoreVoid: false },
      ],
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-meaningless-void-operator": ["error", { checkNever: true }],
      "typescript/no-misused-new": "error",
      "typescript/no-misused-spread": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-this-alias": ["error", { allowDestructuring: false }],
      "typescript/no-unnecessary-parameter-property-assignment": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/no-useless-default-assignment": "error",
      "typescript/no-useless-empty-export": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/require-array-sort-compare": ["error", { ignoreStringArrays: true }],
      "typescript/restrict-template-expressions": [
        "error",
        {
          allowAny: false,
          allowArray: false,
          allowBoolean: false,
          allowNever: false,
          allowNullish: false,
          allowNumber: true,
          allowRegExp: false,
        },
      ],
      "typescript/triple-slash-reference": [
        "error",
        { lib: "always", path: "never", types: "prefer-import" },
      ],
      "typescript/unbound-method": ["error", { ignoreStatic: false }],

      // # suspicious
      "typescript/consistent-return": ["error", { treatUndefinedAsUnspecified: false }],
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-extraneous-class": [
        "error",
        {
          allowConstructorOnly: false,
          allowEmpty: false,
          allowStaticOnly: false,
          allowWithDecorator: false,
        },
      ],
      "typescript/no-unnecessary-boolean-literal-compare": [
        "error",
        {
          allowComparingNullableBooleansToFalse: true,
          allowComparingNullableBooleansToTrue: true,
        },
      ],
      "typescript/no-unnecessary-template-expression": "error",
      "typescript/no-unnecessary-type-arguments": "warn",
      "typescript/no-unnecessary-type-assertion": ["warn", { checkLiteralConstAssertions: true }],
      "typescript/no-unnecessary-type-constraint": "warn",
      "typescript/no-unnecessary-type-conversion": "error",
      "typescript/no-unnecessary-type-parameters": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-type-assertion": "error",

      // # pedantic
      "typescript/ban-ts-comment": [
        "error",
        {
          "ts-check": false,
          "ts-expect-error": "allow-with-description",
          "ts-ignore": true,
          "ts-nocheck": true,
        },
      ],
      // deprecated
      "typescript/ban-types": "off",
      "typescript/no-confusing-void-expression": [
        "error",
        {
          ignoreArrowShorthand: true,
          ignoreVoidOperator: false,
          ignoreVoidReturningFunctions: false,
        },
      ],
      "typescript/no-deprecated": "warn",
      "typescript/no-misused-promises": [
        "error",
        { checksConditionals: true, checksSpreads: true, checksVoidReturn: true },
      ],
      "typescript/no-mixed-enums": "error",
      "typescript/no-unsafe-argument": "warn",
      "typescript/no-unsafe-assignment": "warn",
      "typescript/no-unsafe-call": "warn",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-member-access": ["warn", { allowOptionalChaining: false }],
      "typescript/no-unsafe-return": "warn",
      "typescript/only-throw-error": [
        "error",
        { allowRethrowing: true, allowThrowingAny: false, allowThrowingUnknown: false },
      ],
      "typescript/prefer-enum-initializers": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-nullish-coalescing": [
        "warn",
        {
          ignoreBooleanCoercion: false,
          ignoreConditionalTests: false,
          ignoreIfStatements: false,
          ignoreMixedLogicalExpressions: false,
          ignorePrimitives: false,
          ignoreTernaryTests: false,
        },
      ],
      "typescript/prefer-promise-reject-errors": [
        "error",
        { allowEmptyReject: false, allowThrowingAny: false, allowThrowingUnknown: false },
      ],
      // readonly is preferred but too noisy
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/prefer-ts-expect-error": "error",
      "typescript/related-getter-setter-pairs": "error",
      "typescript/require-await": "warn",
      "typescript/restrict-plus-operands": [
        "error",
        {
          allowAny: false,
          allowBoolean: false,
          allowNullish: false,
          allowNumberAndString: false,
          allowRegExp: false,
          skipCompoundAssignments: false,
        },
      ],
      "typescript/return-await": ["error", "always"],
      "typescript/strict-boolean-expressions": "off",
      "typescript/strict-void-return": "error",
      "typescript/switch-exhaustiveness-check": [
        "warn",
        {
          allowDefaultCaseForExhaustiveSwitch: true,
          considerDefaultExhaustiveForUnions: false,
          requireDefaultForNonUnion: true,
        },
      ],
    },
    supersedes: {
      "typescript/await-thenable": ["unicorn/no-unnecessary-await"],
      "typescript/ban-ts-comment": ["typescript/prefer-ts-expect-error"],
      "typescript/no-implied-eval": ["no-implied-eval"],
      "typescript/only-throw-error": ["no-throw-literal"],
      "typescript/prefer-promise-reject-errors": ["prefer-promise-reject-errors"],
      "typescript/require-await": ["require-await"],
    },
  },
  unicorn: {
    rules: {
      // # correctness
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-invalid-fetch-options": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-spread": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-string-starts-ends-with": "error",

      // # suspicious
      "unicorn/consistent-function-scoping": ["error", { checkArrowFunctions: true }],
      "unicorn/no-accessor-recursion": "error",
      "unicorn/no-array-fill-with-reference-type": "error",
      "unicorn/no-array-reverse": ["error", { allowExpressionStatement: true }],
      "unicorn/no-array-sort": [
        "error",
        { allowAfterSpread: true, allowExpressionStatement: true },
      ],
      "unicorn/no-confusing-array-with": "warn",
      "unicorn/no-instanceof-builtins": [
        "error",
        {
          strategy: "loose",
          // `Error.isError(x)` is not widely available (at 2026-09-27)
          useErrorIsError: false,
        },
      ],
      "unicorn/prefer-add-event-listener": "error",
      "unicorn/require-module-specifiers": "error",
      "unicorn/require-post-message-target-origin": "error",
    },
  },
};
